enum InnerEnumHelper
{
    ENUM_VALUE_1,
    ENUM_VALUE_2,
    ENUM_VALUE_3
};

bitmask InnerBitMaskHelper
{
    @position(0) flag0,
    @position(1) flag1,
    @position(4) flag4,
    @position(6) flag6
};

typedef long InnerAliasHelper;

struct InnerStructureHelper
{
    long field1;
    float field2;
};

union InnerUnionHelper switch (long)
{
    case 0: long longValue;
    case 1: float floatValue;
};

bitset InnerBitsetHelper
{
    bitfield<3> a;
    bitfield<1> b;
    bitfield<4>;
    bitfield<10> c;
    bitfield<12, short> d;
};

typedef short Inner_alias_array_helper[2];
typedef sequence<short> Inner_alias_sequence_helper;
typedef map<long, long> Inner_alias_map_helper;
