#include "helpers/basic_inner_types.idl"

bitset EmptyBitset
{
};

struct Bitset
{
    InnerBitsetHelper var_InnerBitsetHelper;
};

struct EmptyBitset
{
    EmptyBitset var_myemptybitset;
};
