union ForwardUnion;
struct ForwardStruct;

struct ForwardUnionStructure
{
    ForwardUnion var_forwardunion;
};

struct ForwardStructStructure
{
    ForwardStruct var_forwardstruct;
};

struct ForwardUnionChildStructure
{
    ForwardUnionChild var_forwardunionchild;
};

struct ForwardStructChildStructure
{
    ForwardStructChild var_forwardstructchild;
};

struct ModuleStructStructure
{
    ModuleStruct var_modulestruct;
};

struct ForwardUnionChildStructure
{
    ForwardUnionChild var_forwardunionchild;
};

struct ForwardUnionChildStructure
{
    ForwardUnionChild var_forwardunionchild;
};

union ForwardUnion switch (long)
{
    case 0:
        long case_zero;
    case 1:
        long case_one;
};

struct ForwardStruct
{
    long field1;
    float field2;
};

union ForwardUnionChild : ForwardUnion
{
    case 3:
        long case_three;
};

struct ForwardStructChild : ForwardStruct
{
    long field3;
    float field4;
};

module my_module
{
    union ModuleForwardUnion;
    struct ModuleForwardStruct;
}

struct ModuleStruct
{
    my_module::ModuleForwardUnion var_funion;
    my_module::ModuleForwardStruct var_fstruct;
};

module my_module
{    
    union ModuleForwardUnion switch (long)
    {
        case 0:
            long case_zero;
        case 1:
            long case_one;
    };

    struct ModuleForwardStruct
    {
        long field1;
        float field2;
    };
    
    union ModuleForwardUnionChild : ModuleForwardUnion
    {
        case 3:
            long case_three;
    };

    struct ModuleForwardStructChild : ModuleForwardStruct
    {
        long field3;
        float field4;
    };

    struct ModuleForwardUnionStructure
    {
        ModuleForwardUnion var_moduleforwardunion;
    };

    struct ModuleForwardStructStructure
    {
        ModuleForwardStruct var_moduleforwardstruct;
    };

    struct ModuleForwardUnionChildStructure
    {
        ModuleForwardUnionChild var_moduleforwardunionchild;
    };

    struct ModuleForwardStructChildStructure
    {
        ModuleForwardStructChild var_moduleforwardstructchild;
    };
}
