#include "helpers/basic_inner_types.idl"

bitmask MyEmptyBitMask
{
};

struct EnumStructure
{
    InnerEnumHelper var_InnerEnumHelper;
};

struct BitMaskStructure
{
       InnerBitMaskHelper var_InnerBitMaskHelper;
};

struct MyEmptyBitMaskStructure
{
    MyEmptyBitMask var_myemptybitmask;
};

