#include "helpers/basic_inner_types.idl"

bitmask MyEmptyBitMask
{
};

struct EnumStructure
{
    MyEnum var_myenum;
};

struct BitMaskStructure
{
       MyBitMask var_mybitmask;
};

struct MyEmptyBitMaskStructure
{
    MyEmptyBitMask var_myemptybitmask;
};

