#include "structures.idl"

struct StructuresChild : Structures
{
    short var_short;
    unsigned short var_ushort;

    long var_long;
    unsigned long var_ulong;

    long long var_longlong;
    unsigned long long var_ulonglong;
};

struct MyStructureChildChild : MyStructureChild
{
    long long var_longlong2;
    unsigned long long var_ulonglong2;
};
