#include "helpers/basic_inner_types.idl"
#include "bitsets.idl"
#include "structures.idl"

struct InnerStructureHelperChild : InnerStructureHelper
{
    short var_short;
    unsigned short var_ushort;

    long var_long;
    unsigned long var_ulong;

    long long var_longlong;
    unsigned long long var_ulonglong;
};

struct InnerStructureHelperChildChild : InnerStructureHelperChild
{
    long long var_longlong2;
    unsigned long long var_ulonglong2;
};

bitset InnerBitsetHelperChild : InnerBitsetHelper
{
    bitfield<17> z;
};

bitset InnerBitsetHelperEmptyChild : InnerBitsetHelper
{
};

bitset MyEmptyBitsetChild : MyEmptyBitset
{
    bitfield<17> z;
};

bitset MyEmptyBitsetChildEmptyChild : MyEmptyBitsetChild
{
};

struct BitsetChild
{
    InnerBitsetHelperChild var_InnerBitsetHelperchild;
};

struct BitsetEmptyChild
{
    InnerBitsetHelperEmptyChild var_InnerBitsetHelperemptychild;
};

struct EmptyBitsetChild
{
    MyEmptyBitsetChild var_myemptybitsetchild;
};

struct EmptyBitsetChildEmptyChild
{
    MyEmptyBitsetChildEmptyChild var_myemptybitsetchildemptychild;
};



bitmask InnerBitMaskHelperChild : InnerBitMaskHelper
{
    @position(7) flag7
};

bitmask InnerBitMaskHelperEmptyChild : InnerBitMaskHelper
{
};

bitmask MyEmptyBitMaskChild : MyEmptyBitMask
{
    @position(7) flag7
};

bitmask MyEmptyBitMaskChildEmptyChild : MyEmptyBitMaskChild
{
};


struct BitMaskChild
{
    InnerBitMaskHelperChild var_InnerBitMaskHelperchild;
};

struct BitMaskEmptyChild
{
    InnerBitMaskHelperEmptyChild var_InnerBitMaskHelperemptychild;
};

struct EmptyBitMaskChild
{
    MyEmptyBitMaskChild var_myemptybitmaskchild;
};

struct EmptyBitMaskChildEmptyChild
{
    MyEmptyBitMaskChildEmptyChild var_myemptybitmaskchildemptychild;
};



struct InnerStructureHelperChild : InnerStructureHelper
{
    long field3;
    float field4;
};

struct InnerStructureHelperEmptyChild: InnerStructureHelper
{
};

struct MyEmptyStructureChild : MyEmptyStructure
{
    long field3;
    float field4;
};

struct MyEmptyStructureEmptyChild : MyEmptyStructure
{
};

struct StructureChild
{
    InnerStructureHelperChild var_InnerStructureHelperchild;
};

struct StructureEmptyChild
{
    InnerStructureHelperEmptyChild var_InnerStructureHelperemptychild;
};

struct EmptyStructureChild
{
    MyEmptyStructureChild var_myemptystructurechild;
};

struct EmptyStructureEmptyChild
{
    MyEmptyStructureEmptyChild var_myemptystructureemptychild;
};



