#include "helpers/basic_inner_types.idl"

struct MapShort
{
    map<long, short> var_map_short;
};

struct MapUShort
{
    map<long, unsigned short> var_map_ushort;
};

struct MapLong
{
    map<long, long> var_map_long;
};

struct MapULong
{
    map<long, unsigned long> var_map_ulong;
};

struct MapLongLong
{
    map<long, long long> var_map_longlong;
};

struct MapULongLong
{
    map<long, unsigned long long> var_map_ulonglong;
};

struct MapFloat
{
    map<long, float> var_map_float;
};

struct MapDouble
{
    map<long, double> var_map_double;
};

struct MapLongDouble
{
    map<long, long double> var_map_longdouble;
};

struct MapBoolean
{
    map<long, boolean> var_map_boolean;
};

struct MapOctet
{
    map<long, octet> var_map_octet;
};

struct MapChar
{
    map<long, char> var_map_char;
};

struct MapWChar
{
    map<long, wchar> var_map_wchar;
};

struct MapString
{
    map<long, string> var_map_string;
};

struct MapWString
{
    map<long, wstring> var_map_wstring;
};

struct MapBoundedString
{
    map<long, Inner_alias_bounded_string_helper> var_map_bounded_string;
};

struct MapBoundedWString
{
    map<long, Inner_alias_bounded_wstring_helper> var_map_bounded_wstring;
};

struct MapEnum
{
    map<long, InnerEnumHelper> var_map_enum;
};

struct MapBitMask
{
    map<long, InnerBitMaskHelper> var_map_bitmask;
};

struct MapAlias
{
    map<long, InnerAliasHelper> var_map_alias;
};

struct MapShortArray
{
    map<long, Inner_alias_array_helper> var_map_short_array;
};

struct MapSequence
{
    map<long, Inner_alias_sequence_helper> var_map_sequence;
};

struct MapMap
{
    map<long, Inner_alias_map_helper> var_map_map;
};

struct MapUnion
{
    map<long, InnerUnionHelper> var_map_union;
};

struct MapStructure
{
    map<long, InnerStructureHelper> var_map_structure;
};

struct MapBitset
{
    map<long, InnerBitsetHelper> var_map_bitset;
};
    
struct MapKeyShort
{
    map<short, short> var_map_short;
};

struct MapKeyUShort
{
    map<unsigned short, unsigned short> var_map_ushort;
};

struct MapKeyLong
{
    map<long, long> var_map_long;
};

struct MapKeyULong
{
    map<unsigned long, unsigned long> var_map_ulong;
};

struct MapKeyLongLong
{
    map<long long, long long> var_map_longlong;
};

struct MapKeyULongLong
{
    map<unsigned long long, unsigned long long> var_map_ulonglong;
};

struct MapKeyString
{
    map<string, string> var_map_string;
};

struct MapKeyWString
{
    map<wstring, wstring> var_map_wstring;
};

struct BoundedSmallMap
{
    map<long,long,1> var_small_map;
};

struct BoundedLargeMap
{
    map<long,long,41925> var_large_map;
};
