struct Short
{
    short var_short;
};

struct UShort
{
    unsigned short var_ushort;
};

struct Long
{
    long var_long;
};

struct ULong
{
    unsigned long var_ulong;
};

struct LongLong
{
    long long var_longlong;
};

struct ULongLong
{
    unsigned long long var_ulonglong;
};

struct Float
{
    float var_float;
};

struct Double
{
    double var_double;
};

struct LongDouble
{
    long double var_longdouble;
};

struct Boolean
{
    boolean var_boolean;
};

struct Octet

{
    octet var_octet;
};

struct Char
{
    char var_char8;
};

struct WChar
{
    wchar var_char16;
};
