#include "helpers/basic_inner_types.idl"

struct Structures
{
    short var_short;
    unsigned short var_ushort;
    long var_long;
    unsigned long var_ulong;
    long long var_longlong;
    unsigned long long var_ulonglong;
    float var_float;
    double var_double;
    long double var_longdouble;
    boolean var_boolean;
    octet var_octet;
    char var_char8;
    wchar var_char16;
    string var_string8;
    wstring var_string16;

    InnerEnumHelper var_enum;
    InnerBitMaskHelper var_bitmask;
    InnerAliasHelper var_alias;
    short var_array_short[10];
    sequence<long> var_sequence;
    map<long, long> var_map;
    InnerUnionHelper var_union;
    InnerStructureHelper var_structure;
    InnerBitsetHelper var_bitset;
};

struct MyEmptyStructure
{
};

