#include "basic_inner_types.idl"

struct StructShort
{
    short var_short;
};

struct StructUnsignedShort
{
    unsigned short var_ushort;
};

struct StructLong
{
    long var_long;
};

struct StructUnsignedLong
{
    unsigned long var_ulong;
};

struct StructLongLong
{
    long long var_longlong;
};

struct StructUnsignedLongLong
{
    unsigned long long var_ulonglong;
};

struct StructFloat
{
    float var_float;
};

struct StructDouble
{
    double var_double;
};

struct StructBoolean
{
    boolean var_boolean;
};

struct StructOctet
{
    octet var_octet;
};

struct StructChar8
{
    char var_char8;
};

struct StructString
{
    string var_string;
};

struct StructEnum
{
    InnerEnumHelper var_enum;
};

struct StructAlias
{
    InnerAliasHelper var_alias;
};

struct StructShortArray
{
    short var_array_short[10];
};

struct StructSequence
{
    sequence<long> var_sequence;
};

struct StructStructure
{
    InnerStructureHelper var_structure;
};

struct Structures
{
    StructShort var_StructShort;
    StructUnsignedShort var_StructUnsignedShort;
    StructLong var_StructLong;
    StructUnsignedLong var_StructUnsignedLong;
    StructLongLong var_StructLongLong;
    StructUnsignedLongLong var_StructUnsignedLongLong;
    StructFloat var_StructFloat;
    StructDouble var_StructDouble;
    StructBoolean var_StructBoolean;
    StructOctet var_StructOctet;
    StructChar8 var_StructChar8;
    StructString var_StructString;
    StructEnum var_StructEnum;
    StructAlias var_StructAlias;
    StructShortArray var_StructShortArray;
    StructSequence var_StructSequence;
    StructStructure var_StructStructure;
};
