#include "helpers/basic_inner_types.idl"

typedef short alias_array[2];

union Union_Short switch (long)
{
    case 0:
        short a;
};

union Union_UShort switch (long)
{   
    case 1:
        unsigned short b;
};

union Union_Long switch (long)
{ 
    case 2:
        long c;
};

union Union_ULong switch (long)
{ 
    case 3:
        unsigned long d;
};

union Union_LongLong switch (long)
{ 
    case 4:
        long long e;
};

union Union_ULongLOng switch (long)
{ 
    case 5:
        unsigned long long f;
};

union Union_Float switch (long)
{ 
    case 6:
        float g;
};

union Union_Double switch (long)
{ 
    case 7:
        double h;
};

union Union_LongDouble switch (long)
{ 
    case 8:
        long double i;
};

union Union_Boolean switch (long)
{ 
    case 9:
        boolean j;
};

union Union_Octet switch (long)
{ 
    case 10:
        octet k;
};

union Union_Char switch (long)
{ 
    case 11:
        char l;
};

union Union_WChar switch (long)
{ 
    case 12:
        wchar m;
};

union Union_String switch (long)
{ 
    case 13:
        string n;
};

union Union_WString switch (long)
{ 
    case 14:
        wstring o;
};

union Union_MyEnum switch (long)
{ 
    case 15:
        MyEnum p;
};

union Union_MyBitMask switch (long)
{ 
    case 16:
        MyBitMask q; 
};

union Union_MyAlias switch (long)
{ 
    case 17:
        MyAlias r;
};

union Union_Array switch (long)
{ 
    case 18:
        alias_array s;
};

union Union_Sequence switch (long)
{ 
    case 19:
        sequence<short> t; 
};

union Union_Map switch (long)
{ 
    case 20:
        map<long, long> u;
};

union Union_MyUnion switch (long)
{ 
    case 21:
        MyUnion v;
};

union Union_MyStructure switch (long)
{ 
    case 22:
        MyStructure w; 
};

union Union_MyBitset switch (long)
{ 
    case 23:
        MyBitset x;
};

union Union_Discriminator_short switch (short)
{
    case 1:
        long first;
    case -2:
        long long second;
};

union Union_Discriminator_unsigned_short switch (unsigned short)
{
    case 1:
        long first;
    case 2:
        long long second;
};

union Union_Discriminator_long switch (long)
{
    case 1:
        long first;
    case -2:
        long long second;
};

union Union_Discriminator_unsigned_long switch (unsigned long)
{
    case 1:
        long first;
    case 2:
        long long second;
};

union Union_Discriminator_long_long switch (long long)
{
    case 1:
        long first;
    case -2:
        long long second;
};

union Union_Discriminator_unsigned_long_long switch (unsigned long long)
{
    case 1:
        long first;
    case 2:
        long long second;
};

const boolean discriminator_true = TRUE;
const boolean discriminator_false = FALSE;
union Union_Discriminator_boolean switch (boolean)
{
    case discriminator_true:
        long first;
    case discriminator_false:
        long long second;
};

union Union_Discriminator_octet switch (octet)
{
    case 0:
        long first;
    case 1:
        long long second;
};

const char discriminator_a = 'a';
const char discriminator_b = 'b';
union Union_Discriminator_char switch (char)
{
    case discriminator_a:
        long first;
    case discriminator_b:
        long long second;
};

union Union_Discriminator_wchar switch (wchar)
{
    case 'a':
        long first;
    case 'b':
        long long second;
};

union Union_Discriminator_enum switch (MyEnum)
{
    case ENUM_VALUE_1:
        long first;
    case ENUM_VALUE_2:
        long long second;
};

union Union_Discriminator_alias switch (MyAlias)
{
    case 1:
        long first;
    case 2:
        long long second;
};


struct UnionShort
{
    Union_Short union_short;
};

struct UnionUShort
{
    Union_UShort union_ushort;
};

struct UnionLong
{
    Union_Long union_long;
};

struct UnionULong
{
    Union_ULong union_ulong;
};

struct UnionLongLong
{
    Union_LongLong union_long_long;
};

struct UnionULongLong
{
    Union_ULongLOng union_ulong_long;
};

struct UnionFloat
{
    Union_Float union_float;
};

struct UnionDouble
{
    Union_Double union_double;
};

struct UnionLongDouble
{
    Union_LongDouble union_long_double;
};

struct UnionBoolean
{
    Union_Boolean union_boolean;
};

struct UnionOctet
{
    Union_Octet union_octet;
};

struct UnionChar
{
    Union_Char union_char;
};

struct UnionWChar
{
    Union_WChar union_wchar;
};

struct UnionString
{
    Union_String union_string;
};

struct UnionWString
{
    Union_WString union_wstring;
};

struct UnionMyEnum
{
    Union_MyEnum union_my_enum;
};

struct UnionMyBitMask
{
    Union_MyBitMask union_my_bit_mask;
};

struct UnionMyAlias
{
    Union_MyAlias union_my_alias;
};

struct UnionArray
{
    Union_Array union_array;
};

struct UnionSequence
{
    Union_Sequence union_sequence;
};

struct UnionMap
{
    Union_Map union_map;
};

struct UnionMyUnion
{
    Union_MyUnion union_my_union;
};

struct UnionMyStructure
{
    Union_MyStructure union_my_structure;
};

struct UnionMyBitset
{
    Union_MyBitset union_my_bitset;
};

struct UnionDiscriminatorShort
{
    Union_Discriminator_short union_discriminator_short;
};

struct UnionDiscriminatorUShort
{
    Union_Discriminator_unsigned_short union_discriminator_ushort;
};

struct UnionDiscriminatorLong
{
    Union_Discriminator_long union_discriminator_long;
};

struct UnionDiscriminatorULong
{
    Union_Discriminator_unsigned_long union_discriminator_ulong;
};

struct UnionDiscriminatorLongLong
{
    Union_Discriminator_long_long union_discriminator_long_long;
};

struct UnionDiscriminatorULongLong
{
    Union_Discriminator_unsigned_long_long union_discriminator_ulong_long_long;
};

struct UnionDiscriminatorBoolean
{
    Union_Discriminator_boolean union_discriminator_boolean;
};

struct UnionDiscriminatorOctet
{
    Union_Discriminator_octet union_discriminator_octet;
};

struct UnionDiscriminatorChar
{
    Union_Discriminator_char union_discriminator_char;
};

struct UnionDiscriminatorWChar
{
    Union_Discriminator_wchar union_discriminator_wchar;
};

struct UnionDiscriminatorEnum
{
    Union_Discriminator_enum union_discriminator_enum;
};

struct UnionDiscriminatorAlias
{
    Union_Discriminator_alias union_discriminator_alias;
};
